version: '3.8'

services:
  ner-service:
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - MITIE_MODEL_PATH=/app/models/ner_model.dat
      - PORT=8080
      - GIN_MODE=release
    volumes:
      # Mount local models directory (after downloading models)
      - ./models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--timeout=5", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'